/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */
/* Shared C ABI contract of every IoTCom.Net native library (see rust/crates/iotcom-ffi-support). */
#ifndef IOTCOM_COMMON_H
#define IOTCOM_COMMON_H

#include <stddef.h>
#include <stdint.h>

#define IOTCOM_OK 0
#define IOTCOM_ERR_NULL -1
#define IOTCOM_ERR_INVALID_ARG -2
#define IOTCOM_ERR_PANIC -3
#define IOTCOM_ERR_BUFFER_TOO_SMALL -4
#define IOTCOM_ERR_PROTOCOL -5
#define IOTCOM_ERR_BUSY -6
#define IOTCOM_ERR_INTERNAL -99

#ifdef __cplusplus
extern "C" {
#endif

/* ABI version of the library; check it before any other call. */
uint32_t iotcom_abi_version(void);

/* Copies the calling thread's last error (UTF-8, not NUL-terminated) into buf; returns its full length. */
int32_t iotcom_last_error(uint8_t *buf, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* IOTCOM_COMMON_H */
