/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */

#ifndef IOTCOM_MODBUS_H
#define IOTCOM_MODBUS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <iotcom_common.h>

/**
 * Event kinds returned by [`iotcom_modbus_master_poll_event`].
 */
#define IOTCOM_MODBUS_EVENT_RESPONSE 1

/**
 * Timeout event kind.
 */
#define IOTCOM_MODBUS_EVENT_TIMEOUT 2

/**
 * Opaque master handle.
 */
typedef struct ModbusMaster ModbusMaster;

/**
 * Configuration passed to [`iotcom_modbus_master_new`].
 */
typedef struct ModbusMasterCfg {
  /**
   * 0 = TCP, 1 = RTU, 2 = ASCII.
   */
  uint8_t framing;
  /**
   * Response timeout in milliseconds.
   */
  uint32_t timeout_ms;
  /**
   * Max in-flight requests (TCP).
   */
  uint16_t max_in_flight;
  /**
   * Max queued requests.
   */
  uint16_t max_queue;
} ModbusMasterCfg;

/**
 * A tagged event. `data`/`data_len` point into memory owned by the master and stay valid until the
 * next call on the same handle.
 */
typedef struct ModbusEvent {
  /**
   * [`IOTCOM_MODBUS_EVENT_RESPONSE`] or [`IOTCOM_MODBUS_EVENT_TIMEOUT`].
   */
  uint8_t kind;
  /**
   * Responding unit id.
   */
  uint8_t unit_id;
  /**
   * Exception code when the response is an exception PDU, else 0.
   */
  uint8_t exception_code;
  /**
   * Request id.
   */
  uint32_t id;
  /**
   * Response PDU.
   */
  const uint8_t *data;
  /**
   * Response PDU length.
   */
  uintptr_t data_len;
} ModbusEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a master. On success `*out` receives the handle.
 *
 * # Safety
 * `cfg` must point to a valid config and `out` to writable storage.
 */
int32_t iotcom_modbus_master_new(const struct ModbusMasterCfg *cfg, struct ModbusMaster **out);

/**
 * Releases a master. Null is ignored.
 *
 * # Safety
 * `ptr` must come from [`iotcom_modbus_master_new`] and must not be used afterwards.
 */
void iotcom_modbus_master_free(struct ModbusMaster *ptr);

/**
 * Submits a request PDU for `unit_id`. `*out_id` receives the request id.
 *
 * # Safety
 * `pdu` must be valid for `pdu_len` bytes; `out_id` writable.
 */
int32_t iotcom_modbus_master_submit(struct ModbusMaster *ptr,
                                    uint64_t now_us,
                                    uint8_t unit_id,
                                    const uint8_t *pdu,
                                    uintptr_t pdu_len,
                                    uint32_t *out_id);

/**
 * Feeds received bytes.
 *
 * # Safety
 * `data` must be valid for `len` bytes.
 */
int32_t iotcom_modbus_master_handle_input(struct ModbusMaster *ptr,
                                          uint64_t now_us,
                                          const uint8_t *data,
                                          uintptr_t len);

/**
 * Processes expired timers.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_modbus_master_handle_timeout(struct ModbusMaster *ptr, uint64_t now_us);

/**
 * Copies the next frame to transmit into `buf`. Returns the frame length (0 = nothing to send).
 * If `cap` is too small, returns `IOTCOM_ERR_BUFFER_TOO_SMALL` and the frame stays queued
 * (`*out_required` receives the needed size).
 *
 * # Safety
 * `buf` must be valid for `cap` bytes; `out_required` may be null.
 */
int32_t iotcom_modbus_master_poll_transmit(struct ModbusMaster *ptr,
                                           uint8_t *buf,
                                           uintptr_t cap,
                                           uintptr_t *out_required);

/**
 * Retrieves the next event. Returns 1 when `*out` was filled, 0 when no event is pending.
 *
 * # Safety
 * `out` must be writable. `out.data` is valid until the next call on this handle.
 */
int32_t iotcom_modbus_master_poll_event(struct ModbusMaster *ptr, struct ModbusEvent *out);

/**
 * Writes the next deadline (µs) to `*out_deadline_us`. Returns 1 if there is one, 0 otherwise.
 *
 * # Safety
 * `out_deadline_us` must be writable.
 */
int32_t iotcom_modbus_master_poll_timeout(struct ModbusMaster *ptr, uint64_t *out_deadline_us);

/**
 * Number of queued + in-flight requests.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_modbus_master_pending(struct ModbusMaster *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IOTCOM_MODBUS_H */
