/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */

#ifndef IOTCOM_USB_H
#define IOTCOM_USB_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <iotcom_common.h>

/**
 * Status: the USB stack refused the operation (driver, permission, busy interface…).
 */
#define IOTCOM_ERR_USB -30

/**
 * Status: the transfer timed out (no data); the handle stays usable.
 */
#define IOTCOM_ERR_USB_TIMEOUT -31

/**
 * Status: the endpoint stalled (the device rejected the request).
 */
#define IOTCOM_ERR_USB_STALL -32

/**
 * Status: the device is gone.
 */
#define IOTCOM_ERR_USB_DISCONNECTED -33

/**
 * Status: no device matches the id.
 */
#define IOTCOM_ERR_USB_NOT_FOUND -34

/**
 * Opaque HID handle.
 */
typedef struct HidHandle HidHandle;

/**
 * Opaque USB device handle.
 */
typedef struct UsbHandle UsbHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Writes the attached USB devices as a JSON array into `buf`.
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_usb_list(uint8_t *buf, uintptr_t len, uintptr_t *written);

/**
 * Opens the first device matching `VVVV:PPPP[:serial]`.
 *
 * # Safety
 * `id` valid for `id_len` bytes; `out` valid for one pointer write.
 */
int32_t iotcom_usb_open(const uint8_t *id, uintptr_t id_len, struct UsbHandle **out);

/**
 * Releases a device handle (and its claimed interfaces).
 *
 * # Safety
 * `ptr` from [`iotcom_usb_open`], not used afterwards.
 */
void iotcom_usb_free(struct UsbHandle *ptr);

/**
 * Claims an interface (detaching a kernel driver on Linux when `detach` != 0).
 *
 * # Safety
 * `ptr` must be live.
 */
int32_t iotcom_usb_claim(struct UsbHandle *ptr, uint8_t interface, uint8_t detach);

/**
 * Control IN transfer on the default endpoint, through claimed `interface` (0xFF = any claimed).
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_usb_control_in(struct UsbHandle *ptr,
                              uint8_t interface,
                              uint8_t bm_request_type,
                              uint8_t request,
                              uint16_t value,
                              uint16_t index,
                              uint8_t *buf,
                              uintptr_t len,
                              uint32_t timeout_ms,
                              uintptr_t *written);

/**
 * Control OUT transfer on the default endpoint.
 *
 * # Safety
 * `data` valid for `data_len` bytes.
 */
int32_t iotcom_usb_control_out(struct UsbHandle *ptr,
                               uint8_t interface,
                               uint8_t bm_request_type,
                               uint8_t request,
                               uint16_t value,
                               uint16_t index,
                               const uint8_t *data,
                               uintptr_t data_len,
                               uint32_t timeout_ms);

/**
 * Writes to an OUT endpoint (`interrupt` != 0 for interrupt endpoints). Returns the bytes sent.
 *
 * # Safety
 * `data` valid for `data_len` bytes.
 */
int32_t iotcom_usb_write(struct UsbHandle *ptr,
                         uint8_t endpoint,
                         uint8_t interrupt,
                         const uint8_t *data,
                         uintptr_t data_len,
                         uint32_t timeout_ms);

/**
 * Reads one transfer from an IN endpoint into `buf` (rounded up to the max packet size internally).
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_usb_read(struct UsbHandle *ptr,
                        uint8_t endpoint,
                        uint8_t interrupt,
                        uint8_t *buf,
                        uintptr_t len,
                        uint32_t timeout_ms,
                        uintptr_t *written);

/**
 * Writes the HID devices as a JSON array into `buf`.
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_hid_list(uint8_t *buf, uintptr_t len, uintptr_t *written);

/**
 * Opens a HID device by the platform path from [`iotcom_hid_list`].
 *
 * # Safety
 * `path` valid for `path_len` bytes; `out` valid for one pointer write.
 */
int32_t iotcom_hid_open(const uint8_t *path, uintptr_t path_len, struct HidHandle **out);

/**
 * Releases a HID handle.
 *
 * # Safety
 * `ptr` from [`iotcom_hid_open`], not used afterwards.
 */
void iotcom_hid_free(struct HidHandle *ptr);

/**
 * Writes an output report (first byte = report id, 0 when the device uses none). Returns bytes written.
 *
 * # Safety
 * `data` valid for `data_len` bytes.
 */
int32_t iotcom_hid_write(struct HidHandle *ptr,
                         const uint8_t *data,
                         uintptr_t data_len);

/**
 * Reads one input report; `written` = 0 when nothing arrived within `timeout_ms` (-1 = wait forever).
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_hid_read(struct HidHandle *ptr,
                        uint8_t *buf,
                        uintptr_t len,
                        int32_t timeout_ms,
                        uintptr_t *written);

/**
 * Sends a feature report (first byte = report id).
 *
 * # Safety
 * `data` valid for `data_len` bytes.
 */
int32_t iotcom_hid_send_feature(struct HidHandle *ptr, const uint8_t *data, uintptr_t data_len);

/**
 * Reads a feature report; `buf[0]` must hold the report id on entry.
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_hid_get_feature(struct HidHandle *ptr,
                               uint8_t *buf,
                               uintptr_t len,
                               uintptr_t *written);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IOTCOM_USB_H */
