/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */

#ifndef IOTCOM_ZENOH_H
#define IOTCOM_ZENOH_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <iotcom_common.h>

/**
 * Status: the session could not be opened (bad configuration or endpoints).
 */
#define IOTCOM_ERR_ZENOH_OPEN -20

/**
 * Status: zenoh reported an error.
 */
#define IOTCOM_ERR_ZENOH -21

/**
 * Status: the subscriber, queryable or query id is unknown (already undeclared or finished).
 */
#define IOTCOM_ERR_ZENOH_UNKNOWN_ID -22

/**
 * Status: the session was closed.
 */
#define IOTCOM_ERR_ZENOH_CLOSED -23

/**
 * Opaque session handle.
 */
typedef struct ZenohSession ZenohSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Opens a session. `mode` is `peer` or `client` (empty = peer); `connect` and `listen` are
 * comma-separated endpoint lists such as `tcp/127.0.0.1:7447`; `multicast` != 0 enables multicast scouting.
 *
 * # Safety
 * Each string valid for its length (null allowed when the length is 0); `out` valid for one pointer write.
 */
int32_t iotcom_zenoh_open(const uint8_t *mode,
                          uintptr_t mode_len,
                          const uint8_t *connect,
                          uintptr_t connect_len,
                          const uint8_t *listen,
                          uintptr_t listen_len,
                          uint8_t multicast,
                          struct ZenohSession **out);

/**
 * Closes the session (idempotent); the handle must still be freed with [`iotcom_zenoh_free`].
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_zenoh_close(struct ZenohSession *ptr);

/**
 * Closes and releases a session.
 *
 * # Safety
 * `ptr` must come from [`iotcom_zenoh_open`] and must not be used afterwards.
 */
void iotcom_zenoh_free(struct ZenohSession *ptr);

/**
 * Writes session info as JSON (`{"zid":"…","peers":["…"],"routers":["…"]}`) into `buf`; `written` receives the full length.
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_zenoh_info(struct ZenohSession *ptr,
                          uint8_t *buf,
                          uintptr_t len,
                          uintptr_t *written);

/**
 * Publishes a value on a key expression. `encoding` may be empty (= zenoh default).
 *
 * # Safety
 * Each pointer valid for its length (null allowed when the length is 0).
 */
int32_t iotcom_zenoh_put(struct ZenohSession *ptr,
                         const uint8_t *key,
                         uintptr_t key_len,
                         const uint8_t *data,
                         uintptr_t data_len,
                         const uint8_t *encoding,
                         uintptr_t encoding_len);

/**
 * Deletes the value(s) of a key expression.
 *
 * # Safety
 * `key` valid for `key_len` bytes.
 */
int32_t iotcom_zenoh_delete(struct ZenohSession *ptr, const uint8_t *key, uintptr_t key_len);

/**
 * Declares a subscriber; samples arrive as `sample` events carrying the id written to `out_id`.
 *
 * # Safety
 * `key` valid for `key_len` bytes; `out_id` valid for one write.
 */
int32_t iotcom_zenoh_declare_subscriber(struct ZenohSession *ptr,
                                        const uint8_t *key,
                                        uintptr_t key_len,
                                        uint64_t *out_id);

/**
 * Undeclares a subscriber.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_zenoh_undeclare_subscriber(struct ZenohSession *ptr, uint64_t id);

/**
 * Declares a queryable; incoming queries arrive as `query` events and must be answered with
 * [`iotcom_zenoh_reply`] and closed with [`iotcom_zenoh_finish_query`].
 *
 * # Safety
 * `key` valid for `key_len` bytes; `out_id` valid for one write.
 */
int32_t iotcom_zenoh_declare_queryable(struct ZenohSession *ptr,
                                       const uint8_t *key,
                                       uintptr_t key_len,
                                       uint64_t *out_id);

/**
 * Undeclares a queryable.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_zenoh_undeclare_queryable(struct ZenohSession *ptr, uint64_t id);

/**
 * Sends one reply to a query (the key must intersect the query's key expression). May be called
 * several times per query. `encoding` may be empty.
 *
 * # Safety
 * Each pointer valid for its length (null allowed when the length is 0).
 */
int32_t iotcom_zenoh_reply(struct ZenohSession *ptr,
                           uint64_t query,
                           const uint8_t *key,
                           uintptr_t key_len,
                           const uint8_t *data,
                           uintptr_t data_len,
                           const uint8_t *encoding,
                           uintptr_t encoding_len);

/**
 * Sends an error reply to a query.
 *
 * # Safety
 * `data` valid for `data_len` bytes (null allowed when 0).
 */
int32_t iotcom_zenoh_reply_err(struct ZenohSession *ptr,
                               uint64_t query,
                               const uint8_t *data,
                               uintptr_t data_len);

/**
 * Finishes a query: tells the requester that no more replies follow and releases the query id.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_zenoh_finish_query(struct ZenohSession *ptr, uint64_t query);

/**
 * Starts a `get`. Replies arrive as `reply` / `reply_error` events and a final `get_done`, all carrying
 * the id written to `out_id`. `selector` is a key expression with optional `?parameters`;
 * `timeout_ms` = 0 uses 10 s.
 *
 * # Safety
 * `selector` valid for `selector_len`; `data` valid for `data_len` (null allowed when 0); `out_id` valid for one write.
 */
int32_t iotcom_zenoh_get(struct ZenohSession *ptr,
                         const uint8_t *selector,
                         uintptr_t selector_len,
                         const uint8_t *data,
                         uintptr_t data_len,
                         uint32_t timeout_ms,
                         uint64_t *out_id);

/**
 * Copies the oldest queued event (one JSON object) into `buf`. Returns 1 when an event was copied,
 * 0 when the queue is empty, or `IOTCOM_ERR_BUFFER_TOO_SMALL` with the required size in `written`
 * (the event stays queued).
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_zenoh_poll_event(struct ZenohSession *ptr,
                                uint8_t *buf,
                                uintptr_t len,
                                uintptr_t *written);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IOTCOM_ZENOH_H */
