/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */

#ifndef IOTCOM_BLE_H
#define IOTCOM_BLE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <iotcom_common.h>

/**
 * Status: no Bluetooth adapter, or the platform refused access.
 */
#define IOTCOM_ERR_BLE_UNAVAILABLE -20

/**
 * Status: the peripheral id is unknown (not seen in a scan).
 */
#define IOTCOM_ERR_BLE_UNKNOWN_DEVICE -21

/**
 * Status: the characteristic is not on the connected peripheral.
 */
#define IOTCOM_ERR_BLE_UNKNOWN_CHARACTERISTIC -22

/**
 * Status: the operation timed out.
 */
#define IOTCOM_ERR_BLE_TIMEOUT -23

/**
 * Status: the BLE stack reported an error.
 */
#define IOTCOM_ERR_BLE_STACK -24

/**
 * Opaque central handle.
 */
typedef struct BleCentral BleCentral;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a central on the first Bluetooth adapter and starts listening for adapter events.
 *
 * # Safety
 * `out` must be valid for one pointer write.
 */
int32_t iotcom_ble_new(struct BleCentral **out);

/**
 * Releases a central (stops its runtime).
 *
 * # Safety
 * `ptr` must come from [`iotcom_ble_new`] and must not be used afterwards.
 */
void iotcom_ble_free(struct BleCentral *ptr);

/**
 * Writes the adapter description (UTF-8) into `buf`; `written` receives the full length.
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_ble_adapter_info(struct BleCentral *ptr,
                                uint8_t *buf,
                                uintptr_t len,
                                uintptr_t *written);

/**
 * Starts scanning. `services` is a comma-separated UUID filter (empty = all devices).
 *
 * # Safety
 * `services` valid for `services_len` bytes (may be null when the length is 0).
 */
int32_t iotcom_ble_start_scan(struct BleCentral *ptr,
                              const uint8_t *services,
                              uintptr_t services_len);

/**
 * Stops scanning.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_ble_stop_scan(struct BleCentral *ptr);

/**
 * Copies the oldest queued event (one JSON object) into `buf`. Returns 1 when an event was copied,
 * 0 when the queue is empty, or `IOTCOM_ERR_BUFFER_TOO_SMALL` with the required size in `written`
 * (the event stays queued).
 *
 * # Safety
 * `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_ble_poll_event(struct BleCentral *ptr,
                              uint8_t *buf,
                              uintptr_t len,
                              uintptr_t *written);

/**
 * Connects to a peripheral seen in a scan, discovers its services and starts forwarding its notifications.
 *
 * # Safety
 * `id` valid for `id_len` bytes.
 */
int32_t iotcom_ble_connect(struct BleCentral *ptr,
                           const uint8_t *id,
                           uintptr_t id_len,
                           uint32_t timeout_ms);

/**
 * Disconnects a peripheral.
 *
 * # Safety
 * `id` valid for `id_len` bytes.
 */
int32_t iotcom_ble_disconnect(struct BleCentral *ptr, const uint8_t *id, uintptr_t id_len);

/**
 * Writes the services of a connected peripheral as JSON:
 * `[{"uuid":"…","primary":true,"characteristics":[{"uuid":"…","properties":["read","notify"]}]}]`.
 *
 * # Safety
 * `id` valid for `id_len` bytes; `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_ble_services(struct BleCentral *ptr,
                            const uint8_t *id,
                            uintptr_t id_len,
                            uint8_t *buf,
                            uintptr_t len,
                            uintptr_t *written);

/**
 * Reads a characteristic of a connected peripheral into `buf`.
 *
 * # Safety
 * `id`/`ch` valid for their lengths; `buf` valid for `len` bytes; `written` valid for one write.
 */
int32_t iotcom_ble_read(struct BleCentral *ptr,
                        const uint8_t *id,
                        uintptr_t id_len,
                        const uint8_t *ch,
                        uintptr_t ch_len,
                        uint32_t timeout_ms,
                        uint8_t *buf,
                        uintptr_t len,
                        uintptr_t *written);

/**
 * Writes a characteristic (`with_response` != 0 waits for the write response).
 *
 * # Safety
 * `id`/`ch` valid for their lengths; `data` valid for `data_len` bytes.
 */
int32_t iotcom_ble_write(struct BleCentral *ptr,
                         const uint8_t *id,
                         uintptr_t id_len,
                         const uint8_t *ch,
                         uintptr_t ch_len,
                         const uint8_t *data,
                         uintptr_t data_len,
                         uint8_t with_response,
                         uint32_t timeout_ms);

/**
 * Enables (`enable` != 0) or disables notifications or indications of a characteristic.
 *
 * # Safety
 * `id`/`ch` valid for their lengths.
 */
int32_t iotcom_ble_subscribe(struct BleCentral *ptr,
                             const uint8_t *id,
                             uintptr_t id_len,
                             const uint8_t *ch,
                             uintptr_t ch_len,
                             uint8_t enable);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IOTCOM_BLE_H */
