/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */

#ifndef IOTCOM_ISOTP_H
#define IOTCOM_ISOTP_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <iotcom_common.h>

/**
 * Event kinds returned by [`iotcom_isotp_poll_event`].
 */
#define IOTCOM_ISOTP_EVENT_RECEIVED 1

/**
 * A first frame announced `value` bytes.
 */
#define IOTCOM_ISOTP_EVENT_RX_STARTED 2

/**
 * The current message was fully sent.
 */
#define IOTCOM_ISOTP_EVENT_SENT 3

/**
 * A transfer failed; `value` holds the `IsoTpError` code.
 */
#define IOTCOM_ISOTP_EVENT_ERROR 4

/**
 * Opaque channel handle.
 */
typedef struct IsoTpChannel IsoTpChannel;

/**
 * Configuration passed to [`iotcom_isotp_new`]. Flags: bit 0 = pad frames, bit 1 = extended
 * addressing on transmit, bit 2 = extended addressing on receive.
 */
typedef struct IsoTpCfg {
  /**
   * Transmit data length (8 classic; 8–64 CAN FD).
   */
  uint8_t tx_dl;
  /**
   * Padding byte (used when flag bit 0 is set).
   */
  uint8_t padding;
  /**
   * Option flags.
   */
  uint8_t flags;
  /**
   * Extended address prepended on transmit.
   */
  uint8_t ext_addr_tx;
  /**
   * Extended address expected on receive.
   */
  uint8_t ext_addr_rx;
  /**
   * Block size we announce.
   */
  uint8_t block_size;
  /**
   * STmin we announce (raw ISO encoding).
   */
  uint8_t st_min;
  /**
   * Max FC.WAIT frames accepted.
   */
  uint16_t max_wait_frames;
  /**
   * N_Bs timeout in milliseconds.
   */
  uint32_t n_bs_ms;
  /**
   * N_Cr timeout in milliseconds.
   */
  uint32_t n_cr_ms;
  /**
   * Largest message accepted.
   */
  uint32_t max_rx_len;
} IsoTpCfg;

/**
 * A tagged event. `data`/`data_len` stay valid until the next call on the same handle.
 */
typedef struct IsoTpEventC {
  /**
   * Event kind.
   */
  uint8_t kind;
  /**
   * Error code or announced length.
   */
  uint32_t value;
  /**
   * Received message.
   */
  const uint8_t *data;
  /**
   * Received message length.
   */
  uintptr_t data_len;
} IsoTpEventC;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a channel. On success `*out` receives the handle.
 *
 * # Safety
 * `cfg` must point to a valid config and `out` to writable storage.
 */
int32_t iotcom_isotp_new(const struct IsoTpCfg *cfg, struct IsoTpChannel **out);

/**
 * Releases a channel. Null is ignored.
 *
 * # Safety
 * `ptr` must come from [`iotcom_isotp_new`] and must not be used afterwards.
 */
void iotcom_isotp_free(struct IsoTpChannel *ptr);

/**
 * Starts sending a message. Returns `IOTCOM_ERR_BUSY` while another message is in progress.
 *
 * # Safety
 * `data` must be valid for `len` bytes.
 */
int32_t iotcom_isotp_send(struct IsoTpChannel *ptr,
                          uint64_t now_us,
                          const uint8_t *data,
                          uintptr_t len);

/**
 * Feeds the data bytes of one received CAN frame.
 *
 * # Safety
 * `data` must be valid for `len` bytes.
 */
int32_t iotcom_isotp_handle_frame(struct IsoTpChannel *ptr,
                                  uint64_t now_us,
                                  const uint8_t *data,
                                  uintptr_t len);

/**
 * Processes expired timers (and paces consecutive frames by STmin).
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_isotp_handle_timeout(struct IsoTpChannel *ptr, uint64_t now_us);

/**
 * Aborts the current transfers.
 *
 * # Safety
 * `ptr` must be a live handle.
 */
int32_t iotcom_isotp_reset(struct IsoTpChannel *ptr);

/**
 * Copies the next CAN frame payload to transmit into `buf` (64 bytes is always enough).
 * Returns its length, or 0 when nothing is pending.
 *
 * # Safety
 * `buf` must be valid for `cap` bytes.
 */
int32_t iotcom_isotp_poll_frame(struct IsoTpChannel *ptr, uint8_t *buf, uintptr_t cap);

/**
 * Retrieves the next event. Returns 1 when `*out` was filled, 0 when no event is pending.
 *
 * # Safety
 * `out` must be writable. `out.data` is valid until the next call on this handle.
 */
int32_t iotcom_isotp_poll_event(struct IsoTpChannel *ptr, struct IsoTpEventC *out);

/**
 * Writes the next deadline (µs) to `*out_deadline_us`. Returns 1 if there is one, 0 otherwise.
 *
 * # Safety
 * `out_deadline_us` must be writable.
 */
int32_t iotcom_isotp_poll_timeout(struct IsoTpChannel *ptr, uint64_t *out_deadline_us);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IOTCOM_ISOTP_H */
