<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src/IoTCom.Net/IoTCom.Net.csproj" />
  </ItemGroup>
</Project>
