using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using IoTCom.Net.Adapters.Dicom;
using IoTCom.Net.Protocols.Hl7;

namespace IoTCom.Samples.Medical;

/// <summary>Result of an imaging analysis.</summary>
/// <param name="Findings">Findings, each with location.</param>
/// <param name="Impression">One-paragraph impression.</param>
/// <param name="Confidence">low / medium / high.</param>
/// <param name="Urgent">Model considers the study urgent.</param>
/// <param name="Source">Which engine produced it.</param>
/// <param name="MatchesGroundTruth">Whether the planted finding was named (null when unknown).</param>
public sealed record ImagingReport(IReadOnlyList<string> Findings, string Impression, string Confidence, bool Urgent, string Source, bool? MatchesGroundTruth);

/// <summary>
/// Turns streamed data into physician-readable text with an LLM (or a deterministic template when no AI is configured).
/// Prompts state that the data is synthetic and that output is decision support, never a diagnosis.
/// </summary>
public sealed class ClinicalAssistant(AiClient? ai)
{
    /// <summary>Disclaimer shown with every AI output.</summary>
    public static string Disclaimer(string lang) => lang == "id"
        ? "Data sintetis. Alat bantu keputusan untuk demo perangkat lunak — bukan diagnosis; verifikasi secara klinis."
        : "Synthetic data. Decision-support demo — not a diagnosis; verify clinically.";

    /// <summary>True when an LLM is available.</summary>
    public bool HasAi => ai?.Settings.IsConfigured == true;

    /// <summary>Label of the engine in use.</summary>
    public string EngineLabel => HasAi ? ai!.Settings.Label : "rule-based (no AI configured)";

    /// <summary>An SBAR handover note for the patient.</summary>
    public async Task<string> SummarizeAsync(ClinicalSnapshot s, IReadOnlyList<VitalsSample> history, string lang = "en", CancellationToken ct = default)
    {
        if (!HasAi) return Template(s, lang);
        var system = (lang == "id"
            ? "Anda adalah asisten pendukung keputusan klinis untuk dashboard ICU. Tulis dalam Bahasa Indonesia untuk dokter, ringkas, format SBAR (Situation, Background, Assessment, Recommendation) dengan judul tebal Markdown. "
            : "You are a clinical decision-support assistant for an ICU dashboard. Write for physicians, concise, in SBAR format (Situation, Background, Assessment, Recommendation) with bold Markdown headings. ")
            + "The data comes from a SIMULATOR and is synthetic. Use only the data given; do not invent history, labs or medications. " +
            "Interpret trends and the NEWS2 score, name the most likely physiological pattern and its differential, flag what needs urgent action, " +
            "and keep it under 180 words. Do not give a definitive diagnosis.";
        return await ai!.CompleteAsync(system, Describe(s, history), ct: ct);
    }

    /// <summary>Analyzes a rendered image with the vision model (or reports that AI is unavailable).</summary>
    public async Task<ImagingReport> AnalyzeImageAsync(byte[] png, string modality, string studyDescription, SyntheticFinding? groundTruth, string lang = "en", CancellationToken ct = default)
    {
        if (!HasAi)
        {
            return new ImagingReport([], lang == "id"
                ? "AI tidak dikonfigurasi. Atur IOTCOM_AI_ENDPOINT, IOTCOM_AI_KEY dan IOTCOM_AI_VISION_MODEL untuk analisis gambar."
                : "AI is not configured. Set IOTCOM_AI_ENDPOINT, IOTCOM_AI_KEY and IOTCOM_AI_VISION_MODEL to analyse images.",
                "—", false, EngineLabel, null);
        }
        var system =
            "You assist radiologists by pre-reading images. The image is a SYNTHETIC teaching phantom generated by software (schematic anatomy, " +
            "not a real patient). Read it as you would a real study of that type: describe abnormal findings with their side and region " +
            "(image left = patient right), then give an impression with a short differential. If it looks normal, say so. " +
            "Reply ONLY with JSON: {\"findings\":[\"...\"],\"impression\":\"...\",\"confidence\":\"low|medium|high\",\"urgent\":true|false}. " +
            (lang == "id" ? "Tulis isi teks dalam Bahasa Indonesia." : "Write the text values in English.");
        var user = $"Modality: {modality}. Study: {studyDescription}. Pre-read this image.";
        var text = await ai!.CompleteAsync(system, user, png, maxTokens: 8000, ct: ct);
        var report = ParseReport(text, EngineLabel);
        return report with { MatchesGroundTruth = groundTruth is { } g ? Mentions(report, g) : null };
    }

    /// <summary>Compact, factual description of the patient state used as the LLM user prompt.</summary>
    public static string Describe(ClinicalSnapshot s, IReadOnlyList<VitalsSample> history)
    {
        var ic = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        var age = s.Patient.AgeOn(DateOnly.FromDateTime(DateTime.Today));
        sb.AppendLine(ic, $"Patient: {s.Patient.DisplayName}, {(s.Patient.Sex == "F" ? "female" : "male")}, {age} y, ICU bed {s.Bed}. Monitoring window: {s.Window.TotalMinutes:0} min, {s.Samples} samples.");
        var v = s.Latest;
        sb.AppendLine(ic, $"Latest vitals: HR {v.HeartRate:0}/min, RR {v.RespiratoryRate:0}/min, SpO2 {v.SpO2:0}% (room air assumed), BP {v.Systolic:0}/{v.Diastolic:0} mmHg, Temp {v.Temperature:0.0} °C.");
        sb.AppendLine(ic, $"NEWS2: {s.News2.Total} ({s.News2.Risk}); sub-scores: {string.Join(", ", s.News2.Parts.Where(p => p.Value > 0).Select(p => $"{p.Key} {p.Value}"))}.");
        sb.AppendLine(ic, $"Projected NEWS2 in 15 min (linear trend): {s.ProjectedNews2.Total}.");
        sb.AppendLine("Trends (slope per hour, z-score vs patient baseline):");
        foreach (var t in s.Trends) sb.AppendLine(ic, $"- {t.Name}: {t.Latest:0.#}, {t.SlopePerHour:+0.#;-0.#}/h, z {t.ZScore:+0.0;-0.0}");
        if (history.Count > 4)
        {
            sb.AppendLine("Sampled history (time, HR, RR, SpO2, SBP, Temp):");
            var step = Math.Max(1, history.Count / 8);
            for (var i = 0; i < history.Count; i += step)
            {
                var h = history[i];
                sb.AppendLine(ic, $"{h.Time:HH:mm:ss} {h.HeartRate:0} {h.RespiratoryRate:0} {h.SpO2:0} {h.Systolic:0} {h.Temperature:0.0}");
            }
        }
        if (s.Alerts.Count > 0) sb.AppendLine("Rule-based alerts: " + string.Join(" | ", s.Alerts));
        return sb.ToString();
    }

    /// <summary>Deterministic fallback note.</summary>
    public static string Template(ClinicalSnapshot s, string lang)
    {
        var v = s.Latest;
        var ic = CultureInfo.InvariantCulture;
        var rising = s.Trends.Where(t => Math.Abs(t.SlopePerHour) > 0).OrderByDescending(t => Math.Abs(t.ZScore)).Take(2).Select(t => t.Name).ToArray();
        return lang == "id"
            ? string.Create(ic, $"**Situation** — {s.Patient.DisplayName}, bed {s.Bed}: NEWS2 {s.News2.Total} ({s.News2.Risk}).\n**Background** — Pemantauan {s.Window.TotalMinutes:0} menit.\n**Assessment** — HR {v.HeartRate:0}, RR {v.RespiratoryRate:0}, SpO2 {v.SpO2:0}%, TD {v.Systolic:0}/{v.Diastolic:0}, suhu {v.Temperature:0.0} °C. Perubahan terbesar: {string.Join(", ", rising)}. Proyeksi NEWS2 15 menit: {s.ProjectedNews2.Total}.\n**Recommendation** — {(s.News2.Risk >= RiskLevel.Medium ? "Tinjauan klinis segera." : "Lanjutkan pemantauan rutin.")}\n_(Ringkasan berbasis aturan — AI tidak dikonfigurasi.)_")
            : string.Create(ic, $"**Situation** — {s.Patient.DisplayName}, bed {s.Bed}: NEWS2 {s.News2.Total} ({s.News2.Risk}).\n**Background** — {s.Window.TotalMinutes:0} min of monitoring.\n**Assessment** — HR {v.HeartRate:0}, RR {v.RespiratoryRate:0}, SpO2 {v.SpO2:0}%, BP {v.Systolic:0}/{v.Diastolic:0}, Temp {v.Temperature:0.0} °C. Largest changes: {string.Join(", ", rising)}. Projected NEWS2 in 15 min: {s.ProjectedNews2.Total}.\n**Recommendation** — {(s.News2.Risk >= RiskLevel.Medium ? "Urgent clinical review." : "Continue routine monitoring.")}\n_(Rule-based summary — no AI configured.)_");
    }

    /// <summary>Parses the model's JSON (tolerating Markdown fences and extra prose).</summary>
    public static ImagingReport ParseReport(string text, string source)
    {
        var start = text.IndexOf('{', StringComparison.Ordinal);
        var end = text.LastIndexOf('}');
        if (start >= 0 && end > start)
        {
            try
            {
                var node = JsonNode.Parse(text[start..(end + 1)]);
                var findings = node?["findings"] is JsonArray arr ? arr.Select(f => f?.ToString() ?? "").Where(f => f.Length > 0).ToArray() : [];
                return new ImagingReport(findings,
                    node?["impression"]?.ToString() ?? "",
                    node?["confidence"]?.ToString() ?? "unknown",
                    node?["urgent"]?.GetValueKind() == JsonValueKind.True,
                    source, null);
            }
            catch (JsonException) { /* fall through to salvage */ }
        }
        // Salvage truncated JSON: pull out whatever quoted findings / impression made it through.
        var quoted = System.Text.RegularExpressions.Regex.Matches(text, "\"((?:[^\"\\\\]|\\\\.){12,})\"").Select(m => m.Groups[1].Value).ToList();
        var impressionMatch = System.Text.RegularExpressions.Regex.Match(text, "\"impression\"\\s*:\\s*\"((?:[^\"\\\\]|\\\\.)*)");
        if (quoted.Count > 0 && text.TrimStart().StartsWith('{'))
        {
            var impression = impressionMatch.Success ? impressionMatch.Groups[1].Value : string.Empty;
            return new ImagingReport(quoted.Where(q => q != impression).ToArray(), impression, "unknown", false, source + " (partial)", null);
        }
        return new ImagingReport([], text, "unknown", false, source, null);
    }

    /// <summary>Keyword check: did the report name the planted finding?</summary>
    public static bool Mentions(ImagingReport r, SyntheticFinding truth)
    {
        var text = (string.Join(" ", r.Findings) + " " + r.Impression).ToLowerInvariant();
        string[] keys = truth switch
        {
            SyntheticFinding.None => [],
            SyntheticFinding.LungNodule => ["nodule", "nodul", "mass", "opacity", "opasitas"],
            SyntheticFinding.Pneumothorax => ["pneumothorax", "pneumotoraks", "pneumotorak"],
            SyntheticFinding.Consolidation => ["consolidation", "konsolidasi", "pneumonia", "airspace", "infiltrat"],
            SyntheticFinding.Cardiomegaly => ["cardiomegaly", "kardiomegali", "enlarged card", "cardiac enlargement", "pembesaran jantung"],
            SyntheticFinding.PleuralEffusion => ["effusion", "efusi"],
            SyntheticFinding.BrainMass => ["mass", "tumor", "tumour", "lesion", "lesi", "neoplas", "massa"],
            SyntheticFinding.Infarct => ["infarct", "infark", "stroke", "ischem", "ischaem", "iskemi"],
            _ => [],
        };
        if (truth == SyntheticFinding.None)
        {
            // Normal is only a match when the report names none of the abnormal patterns (non-negated).
            return Enum.GetValues<SyntheticFinding>().Where(f => f != SyntheticFinding.None).All(f => !Mentions(r, f));
        }
        // A keyword only counts when its clause is not negated ("no pneumothorax", "without effusion", "tanpa efusi").
        var clauses = text.Split(['.', ';', '\n', '•'], StringSplitOptions.RemoveEmptyEntries);
        return clauses.Any(c => keys.Any(k =>
        {
            var at = c.IndexOf(k, StringComparison.Ordinal);
            if (at < 0) return false;
            var before = c[..at];
            return !Negations.Any(neg => before.Contains(neg, StringComparison.Ordinal));
        }));
    }

    private static readonly string[] Negations = ["no ", "not ", "without", "negative for", "absence", "absent", "free of", "tidak", "tanpa", "bukan"];
}
