<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1812;CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IoTCom.Net.Gallery\IoTCom.Net.Gallery.csproj" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>
</Project>
