//! Regenerates the C headers (`rust/include/*.h`, cbindgen) and the raw C# declarations
//! (`tests/IoTCom.Net.Tests/Interop/Generated/*.g.cs`, csbindgen) of every native library.
//!
//! The .NET packages keep their hand-written `LibraryImport` bindings (SafeHandles, `out` parameters); the
//! generated C# is the reference a test compares them with, so a changed Rust signature fails the build. CI runs
//! `cargo run -p iotcom-bindgen` and then `git diff --exit-code`.
//!
//! Run from the `rust` directory: `cargo run -p iotcom-bindgen`.

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

struct Library {
    /// Crate directory under `crates/native`.
    krate: &'static str,
    /// Shared library name (`iotcom_usb`).
    lib: &'static str,
    /// Generated C# class name.
    class: &'static str,
}

const LIBRARIES: &[Library] = &[
    Library { krate: "iotcom-modbus-native", lib: "iotcom_modbus", class: "ModbusNative" },
    Library { krate: "iotcom-isotp-native", lib: "iotcom_isotp", class: "IsoTpNative" },
    Library { krate: "iotcom-ble-native", lib: "iotcom_ble", class: "BleNative" },
    Library { krate: "iotcom-usb-native", lib: "iotcom_usb", class: "UsbNative" },
    // iotcom-zenoh-native is out of the workspace until zenoh drops the vulnerable lz4_flex 0.10 (RUSTSEC-2026-0041).
];

const NOTICE: &str = "IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil.";

/// The two functions every library exports through `iotcom_ffi_support::export_common!` (a macro, which neither
/// generator expands).
const COMMON_HEADER: &str = r#"/* IoTCom.Net — generated by rust/tools/iotcom-bindgen; do not edit. Built by Gravicode Studios, led by Kang Fadhil. */
/* Shared C ABI contract of every IoTCom.Net native library (see rust/crates/iotcom-ffi-support). */
#ifndef IOTCOM_COMMON_H
#define IOTCOM_COMMON_H

#include <stddef.h>
#include <stdint.h>

#define IOTCOM_OK 0
#define IOTCOM_ERR_NULL -1
#define IOTCOM_ERR_INVALID_ARG -2
#define IOTCOM_ERR_PANIC -3
#define IOTCOM_ERR_BUFFER_TOO_SMALL -4
#define IOTCOM_ERR_PROTOCOL -5
#define IOTCOM_ERR_BUSY -6
#define IOTCOM_ERR_INTERNAL -99

#ifdef __cplusplus
extern "C" {
#endif

/* ABI version of the library; check it before any other call. */
uint32_t iotcom_abi_version(void);

/* Copies the calling thread's last error (UTF-8, not NUL-terminated) into buf; returns its full length. */
int32_t iotcom_last_error(uint8_t *buf, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* IOTCOM_COMMON_H */
"#;

fn normalise(path: &Path) -> Result<(), Box<dyn Error>> {
    // Stable output on every OS: LF line endings, a single trailing newline.
    let text = fs::read_to_string(path)?.replace("\r\n", "\n");
    fs::write(path, format!("{}\n", text.trim_end()))?;
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    let rust = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..").join("..");
    let include = rust.join("include");
    let generated = rust.join("..").join("tests").join("IoTCom.Net.Tests").join("Interop").join("Generated");
    fs::create_dir_all(&include)?;
    fs::create_dir_all(&generated)?;
    fs::write(include.join("iotcom_common.h"), COMMON_HEADER)?;

    for l in LIBRARIES {
        let src = rust.join("crates").join("native").join(l.krate).join("src").join("lib.rs");

        let header = include.join(format!("{}.h", l.lib));
        let guard = format!("{}_H", l.lib.to_uppercase());
        cbindgen::Builder::new()
            .with_src(&src)
            .with_language(cbindgen::Language::C)
            .with_style(cbindgen::Style::Both)
            .with_include_guard(guard)
            .with_header(format!("/* {NOTICE} */"))
            .with_no_includes()
            .with_sys_include("stdbool.h")
            .with_sys_include("stddef.h")
            .with_sys_include("stdint.h")
            .with_sys_include("iotcom_common.h")
            .with_documentation(true)
            .with_cpp_compat(true)
            .generate()?
            .write_to_file(&header);
        normalise(&header)?;

        let cs = generated.join(format!("{}.g.cs", l.class));
        csbindgen::Builder::default()
            .input_extern_file(&src)
            .csharp_dll_name(l.lib)
            .csharp_namespace("IoTCom.Net.Tests.Interop.Generated")
            .csharp_class_name(l.class)
            .csharp_class_accessibility("internal")
            .csharp_use_nint_types(true)
            .csharp_file_header(format!("// {NOTICE}\n#pragma warning disable"))
            .generate_csharp_file(&cs)?;
        normalise(&cs)?;
        println!("{}: include/{}.h, tests/IoTCom.Net.Tests/Interop/Generated/{}.g.cs", l.krate, l.lib, l.class);
    }

    Ok(())
}
