using System.Globalization;
using Google.Protobuf;

namespace IoTCom.Net.Serialization.Protobuf;

/// <summary>A generated Protobuf message type as an <see cref="IPayloadCodec{T}"/>.</summary>
/// <typeparam name="T">A message generated by protoc (or Grpc.Tools).</typeparam>
public sealed class ProtobufCodec<T> : IPayloadCodec<T> where T : IMessage<T>, new()
{
    private static readonly MessageParser<T> Parser = new(() => new T());

    /// <inheritdoc />
    public string ContentType => "application/x-protobuf";

    /// <inheritdoc />
    public byte[] Encode(T value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return value.ToByteArray();
    }

    /// <inheritdoc />
    public T Decode(ReadOnlySpan<byte> payload)
    {
        try
        {
            return Parser.ParseFrom(payload);
        }
        catch (InvalidProtocolBufferException ex)
        {
            throw new ProtocolException($"Invalid {typeof(T).Name} protobuf: {ex.Message}", ex);
        }
    }

    /// <summary>Writes messages with a varint length prefix (the usual framing for streams).</summary>
    public static byte[] EncodeDelimited(IEnumerable<T> messages)
    {
        ArgumentNullException.ThrowIfNull(messages);
        using var ms = new MemoryStream();
        foreach (var m in messages) m.WriteDelimitedTo(ms);
        return ms.ToArray();
    }

    /// <summary>Reads length-prefixed messages.</summary>
    public static IReadOnlyList<T> DecodeDelimited(ReadOnlySpan<byte> data)
    {
        using var ms = new MemoryStream(data.ToArray());
        var list = new List<T>();
        while (ms.Position < ms.Length) list.Add(Parser.ParseDelimitedFrom(ms));
        return list;
    }
}

/// <summary>One field found by <see cref="ProtobufWire.TryInspect"/>.</summary>
/// <param name="Number">Field number.</param>
/// <param name="WireType">Wire type (0 varint, 1 fixed64, 2 length-delimited, 5 fixed32).</param>
/// <param name="Offset">Offset of the key.</param>
/// <param name="Length">Bytes of key and value.</param>
/// <param name="Value">Human-readable value.</param>
/// <param name="Nested">Fields of a length-delimited value that parsed as a message.</param>
public sealed record ProtobufField(int Number, int WireType, int Offset, int Length, string Value, IReadOnlyList<ProtobufField> Nested);

/// <summary>Schema-less inspection of Protobuf bytes: field numbers, wire types and values, nested messages guessed.</summary>
public static class ProtobufWire
{
    /// <summary>Walks the fields of a message; returns false when the bytes are not valid Protobuf.</summary>
    public static bool TryInspect(ReadOnlySpan<byte> data, out IReadOnlyList<ProtobufField> fields, int depth = 0)
    {
        fields = [];
        var list = new List<ProtobufField>();
        var pos = 0;
        while (pos < data.Length)
        {
            var start = pos;
            if (!TryVarint(data, ref pos, out var key) || key == 0 || (key >> 3) == 0) return false;
            var number = (int)(key >> 3);
            var wire = (int)(key & 7);
            string value;
            IReadOnlyList<ProtobufField> nested = [];
            switch (wire)
            {
                case 0:
                    if (!TryVarint(data, ref pos, out var v)) return false;
                    value = v.ToString(CultureInfo.InvariantCulture);
                    break;
                case 1:
                    if (pos + 8 > data.Length) return false;
                    value = BitConverter.ToDouble(data.Slice(pos, 8)).ToString("G6", CultureInfo.InvariantCulture) + " / 0x" + Convert.ToHexString(data.Slice(pos, 8));
                    pos += 8;
                    break;
                case 5:
                    if (pos + 4 > data.Length) return false;
                    value = BitConverter.ToSingle(data.Slice(pos, 4)).ToString("G6", CultureInfo.InvariantCulture) + " / 0x" + Convert.ToHexString(data.Slice(pos, 4));
                    pos += 4;
                    break;
                case 2:
                    if (!TryVarint(data, ref pos, out var len) || len > (ulong)(data.Length - pos)) return false;
                    var bytes = data.Slice(pos, (int)len);
                    pos += (int)len;
                    // Printable text is shown as a string even when it would also parse as a message.
                    var printable = bytes.Length > 0 && bytes.IndexOfAnyExceptInRange((byte)0x20, (byte)0x7E) < 0;
                    if (!printable && depth < 8 && bytes.Length > 0 && TryInspect(bytes, out var inner, depth + 1)) nested = inner;
                    value = printable
                        ? "\"" + System.Text.Encoding.ASCII.GetString(bytes) + "\""
                        : nested.Count > 0 ? $"message ({nested.Count} fields)" : Convert.ToHexString(bytes);
                    break;
                default:
                    return false;
            }

            list.Add(new ProtobufField(number, wire, start, pos - start, value, nested));
        }

        fields = list;
        return true;
    }

    /// <summary>Frame-lane fields (top level) for the traffic tap.</summary>
    public static IReadOnlyList<FrameField> Describe(ReadOnlySpan<byte> data) =>
        TryInspect(data, out var fields)
            ? [.. fields.Select(f => new FrameField($"#{f.Number}", f.Offset, f.Length, f.WireType == 2 && f.Nested.Count > 0 ? FrameFieldKind.Header : FrameFieldKind.Data, f.Value))]
            : [new FrameField("Invalid", 0, data.Length, FrameFieldKind.Error, "not Protobuf")];

    private static bool TryVarint(ReadOnlySpan<byte> d, ref int pos, out ulong value)
    {
        value = 0;
        for (var shift = 0; shift < 64; shift += 7)
        {
            if (pos >= d.Length) return false;
            var b = d[pos++];
            value |= (ulong)(b & 0x7F) << shift;
            if ((b & 0x80) == 0) return true;
        }

        return false;
    }
}
